openapi: '3.0.2'
info:
  title: Snake
  version: '1.0'
servers:
  - url: http://localhost:3000/v1
tags:
  - name: User
components:

  schemas:
    user:
      type: object
      properties:
        username:
          type: string
        fullname:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          format: password
paths:
  /login:
    post:
      description: Inicio de sesion en el sistema
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password

      responses:
        '200':
          description: OK
  /users:
    get:
      summary: Obtiene el listado de usuarios
      description: obtener usuarios del la aplicacion Snake
      operationId: getUsers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
      tags:
        - "User"
    post:
      summary: Crear Usuario Nuevo
      description: ''
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '201':
          description: Operacion Exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      tags:
        - User